" vimrc for omphe
set encoding=utf-8
set nocompatible
set ttyfast

set number

" Vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'


Plugin 'altercation/vim-colors-solarized'
Plugin 'bling/vim-bufferline'
Plugin 'chrisbra/csv.vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'fatih/vim-go'
Plugin 'junegunn/vim-easy-align'
Plugin 'hashivim/vim-hashicorp-tools'
Plugin 'junegunn/goyo.vim'
Plugin 'junegunn/limelight.vim'
Plugin 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
Plugin 'reedes/vim-pencil'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
" Plugin 'vim-airline/vim-airline'
" Plugin 'vim-airline/vim-airline-themes'
Plugin 'derekwyatt/vim-scala'
Plugin 'rodjek/vim-puppet'
Plugin 'uarun/vim-protobuf'
Plugin 'vimwiki/vimwiki'
" Plugin 'artur-shaik/vim-javacomplete2'

Plugin 'Valloric/YouCompleteMe'



call vundle#end()
filetype indent on
filetype plugin on
" End Vundle

" solarized theme
syntax enable
let g:solarized_termcolors=16
set t_Co=16
set background=dark
colorscheme solarized

" airline config
" let g:airline#extensions#tabline#enabled = 1
" let g:airline_theme='solarized'
" let g:airline_powerline_fonts = 1

" powerline setup
let g:Powerline_symbols = "fancy"


set rtp+=/usr/share/powerline/bindings/vim/
set laststatus=2


" For mouse click in NERDTree
:set mouse=a
let g:NERDTreeMouseMode=3

" NERDTree - Start with it open
autocmd VimEnter * NERDTree
" If we opened a file, put focus there, otherwise put focus on the NERDTree
autocmd VimEnter * if argc() | wincmd p | endif

au FileType puppet setlocal isk+=:

" syntastic & shellcheck
:let g:syntastic_sh_shellcheck_exec = '/usr/bin/shellcheck'

" distraction free writing
autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!
set spell spelllang=en_gb

" java setup
autocmd FileType java setlocal omnifunc=javacomplete#Complete:

" templating
"   worth looking into building functions for the groups
if has("autocmd")
  augroup templates
    autocmd BufNewFile *.standup.md 0r ~/.vim/templates/standup.md | execute "%s/<DATE>/" . strftime("%Y-%m-%d") . "/g"
  augroup END

endif
